import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fahim S
 */
public class Toprankedbatsman extends javax.swing.JFrame {
        Connection conn =  null; 
        ResultSet rs=null;
     PreparedStatement ps=null;
    /**
     * Creates new form Toprankedbatsman
     */
    public Toprankedbatsman() {
        initComponents();
        conn = Connect.ConnectDB();
         Table();
    }
    private void Table()
    {
         try{
          
          String s= "select * from batsmanrankt20 ";
          ps=conn.prepareStatement(s);
         rs = ps.executeQuery();
          t20batsmantable.setModel(DbUtils.resultSetToTableModel(rs));
          
      }catch(Exception e){
          
          System.out.println(e);
    } 
         finally{
         try{
         rs.close();
         ps.close();
         }
         catch(Exception e){}
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        c1 = new javax.swing.JTextField();
        rt1 = new javax.swing.JTextField();
        rk1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        rank = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        updatebox = new javax.swing.JTextField();
        searchbox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t20batsmantable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 580));
        setPreferredSize(new java.awt.Dimension(960, 580));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        name1.setBackground(new java.awt.Color(255, 204, 204));
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        getContentPane().add(name1);
        name1.setBounds(40, 190, 110, 30);

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim S\\Desktop\\JAVA\\ICC Pro\\A SAVE.png")); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 160, 110, 40);

        c1.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(c1);
        c1.setBounds(170, 190, 110, 30);

        rt1.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(rt1);
        rt1.setBounds(290, 190, 110, 30);

        rk1.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(rk1);
        rk1.setBounds(420, 190, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 140, 70, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Country");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 140, 80, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Rating");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 140, 80, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Rank");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 140, 60, 20);

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim S\\Desktop\\JAVA\\ICC Pro\\A DELETE.png")); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(610, 230, 110, 40);

        rank.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(rank);
        rank.setBounds(770, 230, 100, 40);

        update.setBackground(new java.awt.Color(0, 255, 0));
        update.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim S\\Desktop\\JAVA\\ICC Pro\\A UPDATE.png")); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(610, 300, 110, 40);

        jButton4.setBackground(new java.awt.Color(0, 255, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim S\\Desktop\\JAVA\\ICC Pro\\A SEARCH.png")); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(610, 370, 110, 40);

        jButton5.setBackground(new java.awt.Color(255, 255, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim S\\Desktop\\JAVA\\ICC Pro\\A BACK.png")); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(820, 480, 90, 35);

        updatebox.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(updatebox);
        updatebox.setBounds(770, 300, 100, 40);

        searchbox.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(searchbox);
        searchbox.setBounds(770, 370, 100, 40);

        t20batsmantable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Country", "Rating", "Rank"
            }
        ));
        jScrollPane1.setViewportView(t20batsmantable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 290, 510, 230);

        jButton3.setBackground(new java.awt.Color(255, 255, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim S\\Desktop\\JAVA\\ICC Pro\\A CLEAN.png")); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(820, 30, 90, 40);

        jButton6.setBackground(new java.awt.Color(255, 204, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("T20 BATSMAN LIST");
        getContentPane().add(jButton6);
        jButton6.setBounds(100, 30, 340, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim S\\Desktop\\JAVA\\ICC Pro\\bat.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 950, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       ResultSet rs=null;
      PreparedStatement ps=null;
      String s=new String();
      String a= name1.getText();
      String b= c1.getText();
      String c= rt1.getText();
      String d = rk1.getText();
      
      //add
      try{
          
          s="Insert into batsmanrankt20 values('"+a+"','"+b+"','"+c+"','"+d+"')";
          ps=conn.prepareStatement(s);
          ps.execute();
          JOptionPane.showMessageDialog(this, "Saved");
          
      }catch(Exception e){
          System.out.println(e);
      }
      finally{
         try{
         rs.close();
         ps.close();
         }
         catch(Exception e){}
         }
      
     Table();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conn = Connect.ConnectDB();
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ResultSet rs=null;
      PreparedStatement ps=null;
      String s=new String();
      String a= name1.getText();
      String b= c1.getText();
      String c= rt1.getText();
      String d = rk1.getText();
      String r= rank.getText();
               try{
          
          s="Delete from batsmanrankt20 where Rank='"+r+"'";
          ps=conn.prepareStatement(s);
          ps.execute();
          
      }catch(Exception e){
          System.out.println("Not");
            // TODO add your handling code here:
      }
               finally{
         try{
         rs.close();
         ps.close();
         }
         catch(Exception e){}
         }
      
     Table();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
                                   // TODO add your handling code here:
       
      
      try{
          
           ResultSet rs=null;
      PreparedStatement ps=null;
      String s=new String();
      String a= name1.getText();
      String b= c1.getText();
      String c= rt1.getText();
      String d= rk1.getText();
      
      String u = updatebox.getText();
          s="update batsmanrankt20 set Name='"+a+"',Country='"+b+"',Rating='"+c+"',Rank='"+d+"'  where Rank='"+u+"'";
          ps=conn.prepareStatement(s);
          ps.executeUpdate();
          //conn.commit();
          
      }catch(Exception e){
          System.out.println("Not");
      }
      finally{
         try{
         rs.close();
         ps.close();
         }
         catch(Exception e){}
         }
      
     Table();
        
      
    }//GEN-LAST:event_updateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ResultSet rs=null;
      PreparedStatement ps=null;
      String s=new String();
      String n= searchbox.getText();
     String i= searchbox.getText();
      
      s="select Rank from batsmanrankt20";
      int flag=0;
      try{
          
          ps=conn.prepareStatement(s);
          rs=ps.executeQuery();
          while(rs.next()){
              //System.out.println(rs.getString("Name")+ " "+rs.getString("Id") );
              //System.out.println(rs.getString("Id"));
          if(i.equals(rs.getString("Rank"))){
              //JOptionPane.showMessageDialog(this, "Found");
              flag=1;
              break;
          }
          }
          if(flag==1)JOptionPane.showMessageDialog(this, "Found");
          else {
              JOptionPane.showMessageDialog(this, "Not Found");
          }
          }
          
          
      catch(Exception e){
          
      }
      finally{
         try{
         rs.close();
         ps.close();
         }
         catch(Exception e){}
         }
      
     Table();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        t20 f= new t20();
        f.setVisible(true);
        this.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Toprankedbatsman f= new Toprankedbatsman();
       f.setVisible(true);
       this.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toprankedbatsman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toprankedbatsman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toprankedbatsman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toprankedbatsman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Toprankedbatsman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField rank;
    private javax.swing.JTextField rk1;
    private javax.swing.JTextField rt1;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTable t20batsmantable;
    private javax.swing.JButton update;
    private javax.swing.JTextField updatebox;
    // End of variables declaration//GEN-END:variables
}
